export const salesData = {
  "2022": [
    { month: "Jan", sales: 120 },
    { month: "Feb", sales: 200 },
    { month: "Mar", sales: 150 },
    { month: "Apr", sales: 300 },
    { month: "May", sales: 250 },
    { month: "Jun", sales: 400 },
    { month: "Jul", sales: 350 },
    { month: "Aug", sales: 500 },
    { month: "Sep", sales: 450 },
    { month: "Oct", sales: 600 },
    { month: "Nov", sales: 700 },
    { month: "Dec", sales: 800 },
  ],
  "2023": [
    { month: "Jan", sales: 100 },
    { month: "Feb", sales: 180 },
    { month: "Mar", sales: 160 },
    { month: "Apr", sales: 280 },
    { month: "May", sales: 260 },
    { month: "Jun", sales: 420 },
    { month: "Jul", sales: 360 },
    { month: "Aug", sales: 520 },
    { month: "Sep", sales: 480 },
    { month: "Oct", sales: 640 },
    { month: "Nov", sales: 720 },
    { month: "Dec", sales: 850 },
  ],
  "2024": [
    { month: "Jan", sales: 130 },
    { month: "Feb", sales: 210 },
    { month: "Mar", sales: 170 },
    { month: "Apr", sales: 310 },
    { month: "May", sales: 270 },
    { month: "Jun", sales: 430 },
    { month: "Jul", sales: 370 },
    { month: "Aug", sales: 530 },
    { month: "Sep", sales: 490 },
    { month: "Oct", sales: 650 },
    { month: "Nov", sales: 730 },
    { month: "Dec", sales: 870 },
  ],
};
